### ISSUE TITLE
webpack과 babel설정 완료해서 boilerplate 만들어서 각자의 레포지토리에 올리기

### ISSUE THREAD

**Issue by parkjihwanjay** [woowa-techcamp-2020/todo-15#1]
## Description
> webpack, babel에 대해 공부하고 실습해본다.

## todos
- [x] webpack 설정
- [x] babel 설정
- [x] sourceMap 설정
- [x] 전세계 1%범위에서 사용되는 브라우저에서 동작가능하도록 배포파일을 생성
- [x] css 와 image도 import 되도록 해야 함
- [x] 환경설정을 끝내면, 본인만의 boilerplate를 만들어서 개인 계정의 github에 올린다.
