### ISSUE TITLE
drag and drop 버그 수정

### ISSUE THREAD

**Issue by haerang94** [woowa-techcamp-2020/todo-15#122]
##Descripiton
> 드래그 앤 드랍 관련 몇몇 버그 수정합니다.

## todos
- [x] 더블 클릭 시 모달 창이 열리지 않는 버그 수정 
- [x] 삭제 시 droppable 태그가 같이 삭제 되지 않는 버그 수정 
- [x] 컬럼의 실제 투두리스트 아이템 개수 다른 버그 수정
