### ISSUE TITLE
투두리스트 렌더링해주는 함수 구현

### ISSUE THREAD

**Issue by haerang94** [woowa-techcamp-2020/todo-15#28]
##Descripiton
> 홈페이지 로딩시에 데이터베이스에 저장된 각 투두리스트를 렌더링해주는 함수와 각 투두리스트의 마크업을 리턴해주는 함수를 각각의 모듈로
만든다

## todos
- [x] 템플릿 리터럴 형태로 전달받은 값으로 각 투두리스트를 만드는 모듈함수를 만든다.
- [x] 리턴받은 각 투두리스트를 각 컨테이너에 추가해주면서 렌더링하는 함수를 만든다.
- [x] app.js에서 홈페이지 로딩시 투두리스트가 렌더링되도록 각 함수들을 묶어서 구현한다.
