### ISSUE TITLE
새로운 컬럼을 추가하는 함수 생성

### ISSUE THREAD

**Issue by haerang94** [woowa-techcamp-2020/todo-15#30]
##Descripiton
> 새로운 컬럼을 추가할 수 있는 함수를 생성한다

## todos
- [x] 새 컨테이너를 마크업 형태로 작성해 반환하는 함수를 구현한다. 
- [x] 새로 만든 컨테이너를 추가하는 함수를 구현한다.
- [x] app.js 파일에서 import하여 테스트한다.
