### ISSUE TITLE
[express] middleware를 통한 리팩토링

### ISSUE THREAD

**Issue by parkjihwanjay** [woowa-techcamp-2020/todo-15#40]
##Descripiton
> 콜백함수의 임무가 너무 많다. middleware를 통해 모듈화를 하자 

## todos
- [ ] GET /api/todo 리팩토링
- [ ] POST /api/todo 리팩토링
- [ ] db와 관련된 로직 middleware로 만들기
- [ ] validate와 관련된 로직 middleware로 만들기
