### ISSUE TITLE
새로운 todolist의 id값 정하는 방식 정하기 및 구현하기

### ISSUE THREAD

**Issue by haerang94** [woowa-techcamp-2020/todo-15#80]
##Descripiton
> 투두리스트를 추가하고 삭제하는 과정에서 새로 추가되는 투두리스트의 idx(순서)가 기존의 투두리스트보다 우선인 경우가 생겼습니다.
id값을 단순히 현재 투두리스트의 개수 +1 했던 경우 때문입니다. 새로 id값을 어떻게 정할지 의논하고 다시 구현할 필요가 있습니다.

## todos
- [x] id값 정하는 방식 의논하기
- [x] 정한 방식대로 새로 id값 구현하기
- [x] 제대로 추가 및 렌더링이 동작하는 지 테스트하기
