### ISSUE TITLE
컬럼 렌더링 관련 버그 수정, 유일한 컬럼들의 id를 반환해주는 api 작성

### ISSUE THREAD

**Issue by haerang94** [woowa-techcamp-2020/todo-15#85]
##Descripiton
> columns 개수만큼 for문을 돌려 컬럼을 생성하는 함수에 버그가 있어 실제 distinct한 컬럼 행만을 받아와 컬럼을 만들어주는 api를 만들어 함수를 수정

## todos
- [x] distinctColumns api를 만든다
- [x] 기존 renderColumns 관련 함수를 수정한다
- [x] api를 연결하고 테스트한다
