### ISSUE TITLE
[메인 페이지] 마크업 완성

### ISSUE THREAD

**Issue by parkjihwanjay** [woowa-techcamp-2020/todo-15#9]
##Descripiton
> 메인 페이지 html 구조 짜기

## todos
- [x] html 마크업 작성하기 
- [x] scss 문법으로 css 작성하기
- [x] font와 아이콘 도입하기
