### ISSUE TITLE
모달 ui 생성 및 투두리스트 아이템 더블클릭 이벤트 함수 작성

### ISSUE THREAD

**Issue by haerang94** [woowa-techcamp-2020/todo-15#90]
##Descripiton
> 각 투두리스트 아이템을 더블 클릭했을 때 모달 창이 나타나 내용을 수정할 수 있도록 한다

## todos
- [x] 모달 창 ui 및 css 작성
- [x] 더블클릭 이벤트 리스너 생성해서 내용 수정하도록 구현 (프론트)
- [x] 투두리스트 업데이트 api 생성해서 연결
